// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactsmanager/contact.proto

package contactsmanager.proto;

public final class Contact {
  private Contact() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PContactOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string firstName = 1;
    boolean hasFirstName();
    String getFirstName();
    
    // optional string middleName = 2;
    boolean hasMiddleName();
    String getMiddleName();
    
    // optional string lastName = 3;
    boolean hasLastName();
    String getLastName();
    
    // optional string mobile = 4;
    boolean hasMobile();
    String getMobile();
    
    // optional string homepage = 5;
    boolean hasHomepage();
    String getHomepage();
  }
  public static final class PContact extends
      com.google.protobuf.GeneratedMessage
      implements PContactOrBuilder {
    // Use PContact.newBuilder() to construct.
    private PContact(Builder builder) {
      super(builder);
    }
    private PContact(boolean noInit) {}
    
    private static final PContact defaultInstance;
    public static PContact getDefaultInstance() {
      return defaultInstance;
    }
    
    public PContact getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contactsmanager.proto.Contact.internal_static_contactsmanager_proto_PContact_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contactsmanager.proto.Contact.internal_static_contactsmanager_proto_PContact_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string firstName = 1;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object firstName_;
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          firstName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string middleName = 2;
    public static final int MIDDLENAME_FIELD_NUMBER = 2;
    private java.lang.Object middleName_;
    public boolean hasMiddleName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMiddleName() {
      java.lang.Object ref = middleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          middleName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMiddleNameBytes() {
      java.lang.Object ref = middleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        middleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string lastName = 3;
    public static final int LASTNAME_FIELD_NUMBER = 3;
    private java.lang.Object lastName_;
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          lastName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mobile = 4;
    public static final int MOBILE_FIELD_NUMBER = 4;
    private java.lang.Object mobile_;
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mobile_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string homepage = 5;
    public static final int HOMEPAGE_FIELD_NUMBER = 5;
    private java.lang.Object homepage_;
    public boolean hasHomepage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getHomepage() {
      java.lang.Object ref = homepage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          homepage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHomepageBytes() {
      java.lang.Object ref = homepage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        homepage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      firstName_ = "";
      middleName_ = "";
      lastName_ = "";
      mobile_ = "";
      homepage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMiddleNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMobileBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getHomepageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMiddleNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMobileBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getHomepageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static contactsmanager.proto.Contact.PContact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static contactsmanager.proto.Contact.PContact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static contactsmanager.proto.Contact.PContact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(contactsmanager.proto.Contact.PContact prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements contactsmanager.proto.Contact.PContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return contactsmanager.proto.Contact.internal_static_contactsmanager_proto_PContact_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return contactsmanager.proto.Contact.internal_static_contactsmanager_proto_PContact_fieldAccessorTable;
      }
      
      // Construct using contactsmanager.proto.Contact.PContact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        middleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        homepage_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return contactsmanager.proto.Contact.PContact.getDescriptor();
      }
      
      public contactsmanager.proto.Contact.PContact getDefaultInstanceForType() {
        return contactsmanager.proto.Contact.PContact.getDefaultInstance();
      }
      
      public contactsmanager.proto.Contact.PContact build() {
        contactsmanager.proto.Contact.PContact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private contactsmanager.proto.Contact.PContact buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        contactsmanager.proto.Contact.PContact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public contactsmanager.proto.Contact.PContact buildPartial() {
        contactsmanager.proto.Contact.PContact result = new contactsmanager.proto.Contact.PContact(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.middleName_ = middleName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.homepage_ = homepage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof contactsmanager.proto.Contact.PContact) {
          return mergeFrom((contactsmanager.proto.Contact.PContact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(contactsmanager.proto.Contact.PContact other) {
        if (other == contactsmanager.proto.Contact.PContact.getDefaultInstance()) return this;
        if (other.hasFirstName()) {
          setFirstName(other.getFirstName());
        }
        if (other.hasMiddleName()) {
          setMiddleName(other.getMiddleName());
        }
        if (other.hasLastName()) {
          setLastName(other.getLastName());
        }
        if (other.hasMobile()) {
          setMobile(other.getMobile());
        }
        if (other.hasHomepage()) {
          setHomepage(other.getHomepage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              firstName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              middleName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              lastName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mobile_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              homepage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string firstName = 1;
      private java.lang.Object firstName_ = "";
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFirstName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      void setFirstName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
      }
      
      // optional string middleName = 2;
      private java.lang.Object middleName_ = "";
      public boolean hasMiddleName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMiddleName() {
        java.lang.Object ref = middleName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          middleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMiddleName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        middleName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMiddleName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        middleName_ = getDefaultInstance().getMiddleName();
        onChanged();
        return this;
      }
      void setMiddleName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        middleName_ = value;
        onChanged();
      }
      
      // optional string lastName = 3;
      private java.lang.Object lastName_ = "";
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLastName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      void setLastName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
      }
      
      // optional string mobile = 4;
      private java.lang.Object mobile_ = "";
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMobile(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mobile_ = value;
        onChanged();
        return this;
      }
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      void setMobile(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        mobile_ = value;
        onChanged();
      }
      
      // optional string homepage = 5;
      private java.lang.Object homepage_ = "";
      public boolean hasHomepage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getHomepage() {
        java.lang.Object ref = homepage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          homepage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHomepage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        homepage_ = value;
        onChanged();
        return this;
      }
      public Builder clearHomepage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        homepage_ = getDefaultInstance().getHomepage();
        onChanged();
        return this;
      }
      void setHomepage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        homepage_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:contactsmanager.proto.PContact)
    }
    
    static {
      defaultInstance = new PContact(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:contactsmanager.proto.PContact)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contactsmanager_proto_PContact_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contactsmanager_proto_PContact_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035contactsmanager/contact.proto\022\025contact" +
      "smanager.proto\"e\n\010PContact\022\021\n\tfirstName\030" +
      "\001 \001(\t\022\022\n\nmiddleName\030\002 \001(\t\022\020\n\010lastName\030\003 " +
      "\001(\t\022\016\n\006mobile\030\004 \001(\t\022\020\n\010homepage\030\005 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_contactsmanager_proto_PContact_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_contactsmanager_proto_PContact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contactsmanager_proto_PContact_descriptor,
              new java.lang.String[] { "FirstName", "MiddleName", "LastName", "Mobile", "Homepage", },
              contactsmanager.proto.Contact.PContact.class,
              contactsmanager.proto.Contact.PContact.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
